Proper Album and Track add
Junction Table added
Tracks now get processed before being added
Service Interfaces and Repositories in use

error: artists don't get added to tracks
reason: controller doesent process the artist id from form correctly
Co-Authored-By: Aneta Solunska <100601635+Solunska@users.noreply.github.com>